create table TB_FLUXO_CAIXA
(
    co_fluxo_caixa        int auto_increment,
    dt_cadastro           datetime     null,
    dt_realizado          date         null,
    dt_vencimento         date         null,
    nu_valor              float(12, 2) null,
    nu_valor_pago         float(12, 2) null,
    ds_descricao          text         null,
    tp_fluxo              int(1)       null comment '1 - Entrada / 2 - Saída',
    tp_pagamento          int(1)       null comment 'GRATIS = 0 / DINHEIRO = 1 / CARTAO_DEBITO = 2 / CARTAO_CREDITO = 3 /  PIX = 4 / BOLETO = 5 / PROMISSORIA = 6 / CHEQUE = 7 / PARCELAMENTO_PROPRIO = 8 / OUTROS = 9 ',
    st_pagamento          int(1)       null comment '1 - A Pagar / 2 - A Receber / 3 - Pago / 4 - Em Atraso ',
    co_categoria_fc       int          not null,
    co_categoria_fc_filha int          not null,
    co_categoria_fc_neta  int          not null,
    co_centro_custo       int          not null,
    co_conta_bancaria     int          not null,
    co_representacao      int          not null,
    co_usuario            int(10)      not null,
    co_assinante          int          not null,
    primary key (co_fluxo_caixa, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo,
                 co_conta_bancaria, co_representacao, co_usuario, co_assinante)
);

INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (1, '2023-02-08 12:23:36', '2023-01-20', null, null, 400, 'Adiantamento de passagem para viagem', 1, 1, 3, 5, 13, 55, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (2, '2023-02-08 12:35:27', '2023-01-23', null, null, 3700, 'Era 4mil porem sobrou 300', 1, 1, 3, 5, 13, 55, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (3, '2023-02-08 12:37:52', '2023-02-01', null, null, 1800, 'Pagamento Toalhinhas de personagem', 1, 4, 3, 5, 13, 55, 0, 2, 21, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (4, '2023-02-08 12:41:36', '2023-02-01', null, null, 1800, 'COmpra de toalhas de personagem 52 duzias', 2, 4, 3, 2, 3, 10, 0, 2, 22, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (5, '2023-02-08 15:42:40', '2023-01-22', null, null, 560, 'Passagem viagem Brás SP', 2, 4, 3, 2, 15, 63, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (6, '2023-02-08 15:44:14', '2023-01-22', null, null, 80, 'Locomoção na viagem', 2, 3, 3, 2, 15, 64, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (7, '2023-02-08 15:45:47', '2023-01-22', null, null, 80, 'Pago cartão C6 CRÉDITO', 1, 3, 3, 5, 13, 55, 0, 3, 21, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (8, '2023-02-08 15:48:00', '2023-01-22', null, null, 260, 'Custo da alimentação da viagem toda', 2, 3, 3, 2, 15, 66, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (9, '2023-02-08 15:56:23', '2023-01-25', null, null, 94.25, 'Hospedagem do site', 2, 3, 3, 4, 10, 47, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (10, '2023-02-08 15:58:33', '2023-01-22', null, null, 3600, 'Compra das mochilas', 2, 3, 3, 2, 3, 10, 0, 3, 6, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (11, '2023-02-08 16:09:20', '2023-01-22', null, null, 150, 'Compra dos talheres inox', 2, 3, 3, 2, 3, 10, 0, 3, 2, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (12, '2023-02-08 16:11:03', '2023-01-22', null, null, 1530, 'Materiais diversos', 2, 1, 3, 2, 3, 10, 0, 2, 3, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (13, '2023-02-08 16:12:12', '2023-01-22', null, null, 220, 'Compra de pilhas AAA e AA', 2, 4, 3, 2, 3, 10, 0, 2, 4, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (15, '2023-02-08 16:16:00', '2023-01-23', null, null, 579, 'Compra porta lapis', 2, 1, 3, 2, 3, 10, 0, 2, 7, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (16, '2023-02-08 19:07:38', '2023-01-23', null, null, 112, 'Compras porta lápis', 2, 1, 3, 2, 3, 10, 0, 2, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (17, '2023-02-08 19:13:40', '2023-01-23', null, null, 712.5, 'Compras dos panos de prato e panos de chão', 2, 1, 3, 2, 3, 10, 0, 2, 5, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (19, '2023-02-08 19:17:40', '2023-01-24', null, null, 95, 'Porta lápis 2 ziper', 1, 4, 3, 1, 1, 3, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (21, '2023-02-08 19:21:19', '2023-01-24', null, null, 340, 'Porta lápis e mochila', 1, 4, 3, 1, 1, 3, 0, 3, 10, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (22, '2023-02-08 19:23:13', '2023-01-25', null, null, 410, 'Mochilas e portas lápis', 1, 4, 3, 1, 1, 3, 0, 3, 24, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (24, '2023-02-08 19:25:04', '2023-02-08', null, null, 532, 'Porta lápis', 1, 4, 3, 1, 1, 3, 0, 3, 25, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (25, '2023-02-08 19:29:18', '2023-02-13', '2023-02-05', 162, 162, 'Mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 26, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (26, '2023-02-08 19:30:50', '2023-01-26', null, null, 100, 'Mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (29, '2023-02-08 19:34:34', '2023-01-31', null, null, 108, 'Pago depois pix', 1, 1, 3, 1, 1, 1, 0, 2, 10, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (30, '2023-02-08 19:36:17', '2023-02-10', '2023-02-07', 492, 492, 'Toalha personagem e mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 11, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (31, '2023-02-08 19:37:24', null, '2023-02-10', 102, null, 'Mochilas', 1, 4, 4, 1, 1, 3, 0, 3, 27, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (33, '2023-02-08 19:40:45', '2023-01-31', null, null, 30, '1 dz colher inox', 1, 1, 3, 1, 1, 1, 0, 2, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (34, '2023-02-08 19:41:58', '2023-02-01', null, null, 543, 'Toalhas personagem e porta lapis e mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 12, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (35, '2023-02-08 19:43:04', '2023-02-10', '2023-02-08', 200, 200, 'Toalhas personagem e porta lapis e mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 12, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (38, '2023-02-08 19:46:29', '2023-02-03', null, null, 162, 'Toalhas pers.', 1, 1, 3, 1, 1, 1, 0, 2, 24, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (39, '2023-02-08 19:47:56', '2023-02-01', null, null, 175, 'Toalhas', 1, 1, 3, 1, 1, 1, 0, 2, 29, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (41, '2023-02-08 19:50:00', '2023-03-04', '2023-02-15', 312, 312, 'Toalhas mochilas e porta lapis', 1, 4, 3, 1, 1, 3, 0, 3, 16, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (42, '2023-02-08 19:51:20', '2023-02-03', null, null, 237, 'toalhas', 1, 1, 3, 1, 1, 1, 0, 2, 17, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (43, '2023-02-08 19:52:53', '2023-02-05', null, null, 54, 'Toalhas', 1, 1, 3, 1, 1, 1, 0, 2, 30, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (44, '2023-02-08 19:54:05', '2023-02-05', null, null, 156, 'Mochilas', 1, 1, 3, 1, 1, 1, 0, 2, 28, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (45, '2023-02-09 14:09:31', '2023-02-06', '2023-02-03', 420, 420, '', 1, 4, 3, 1, 1, 3, 0, 3, 9, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (46, '2023-02-09 14:14:15', '2023-02-06', null, null, 208, '', 1, 1, 3, 1, 1, 1, 0, 2, 18, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (47, '2023-02-09 14:14:56', '2023-02-06', null, null, 125, '', 1, 4, 3, 1, 1, 3, 0, 3, 19, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (48, '2023-02-09 14:16:57', '2023-02-15', '2023-02-15', 276, 276, '', 1, 4, 3, 1, 1, 3, 0, 3, 31, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (49, '2023-02-09 14:19:12', '2023-02-23', '2023-02-15', 108, 108, '', 1, 4, 3, 1, 1, 3, 0, 3, 32, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (50, '2023-02-09 14:20:40', '2023-02-08', null, null, 54, '', 1, 1, 3, 1, 1, 1, 0, 2, 33, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (51, '2023-02-09 14:23:13', '2023-02-07', '2023-02-06', 687, 687, 'Toalhas personagem e porta lapis', 1, 4, 3, 1, 1, 3, 0, 3, 13, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (52, '2023-02-09 14:26:46', '2023-02-07', null, null, 364, 'Pagamento Porta Lápis', 2, 4, 3, 6, 14, 60, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (53, '2023-02-09 14:28:21', '2023-02-07', '2023-02-01', 386, 386, 'Mochilas e Porta Lápis', 1, 4, 3, 1, 1, 3, 0, 3, 8, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (54, '2023-02-09 14:33:15', '2023-01-26', '2023-01-26', 100, 100, 'Mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (55, '2023-02-09 14:43:05', '2023-01-27', null, null, 180, 'Pix Hélio Ferreira', 2, 4, 3, 6, 14, 67, 0, 3, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (57, '2023-02-09 14:48:02', '2023-01-31', null, null, 600, '', 2, 4, 3, 6, 14, 67, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (58, '2023-02-09 14:49:09', '2023-01-30', null, null, 700, '', 2, 4, 3, 6, 14, 67, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (59, '2023-02-09 14:51:04', '2023-02-09', '2023-02-08', 312, 312, 'Toalhas mochilas e porta lapis', 1, 4, 3, 1, 1, 3, 0, 3, 16, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (60, '2023-02-09 14:54:28', '2023-01-20', null, null, 6360, '', 1, 4, 3, 5, 13, 55, 0, 3, 21, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (61, '2023-02-09 15:19:10', '2023-01-23', null, null, 112, 'Porta lápis 2 xíper Troca de produto calça e blusa', 1, 1, 3, 1, 1, 1, 0, 2, 34, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (62, '2023-02-09 22:38:35', '2023-03-04', '2023-02-22', 150, 150, 'Pct toalhas coloridas', 1, 4, 3, 1, 1, 3, 0, 3, 16, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (63, '2023-02-09 22:40:41', '2023-02-09', '2023-02-08', 200, 200, 'Toalhas mochilas', 1, 4, 3, 1, 1, 3, 0, 3, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (64, '2023-02-09 22:44:37', '2023-02-27', '2023-02-15', 267, 200, 'Toalhas personagem 39 unidades', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (65, '2023-02-09 22:46:45', '2023-02-03', null, null, 70, '', 2, 1, 3, 2, 6, 23, 0, 2, 1, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (66, '2023-02-10 10:33:19', '2023-02-08', '2023-02-03', 138, 138, 'Porta lapis', 1, 4, 3, 1, 1, 3, 0, 3, 23, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (71, '2023-02-12 15:53:29', '2023-02-13', '2023-02-14', 750, 750, 'Toalhas coloridas', 2, 4, 3, 2, 3, 10, 0, 5, 22, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (72, '2023-02-12 15:54:32', '2023-02-13', '2023-02-14', 1050, 1050, 'Toalhas Personagem', 2, 4, 3, 2, 3, 10, 0, 3, 22, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (73, '2023-02-14 14:30:22', '2023-02-10', null, null, 137, 'Toalha', 1, 1, 3, 1, 1, 3, 0, 2, 35, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (74, '2023-02-14 14:36:13', '2023-02-13', null, null, 370, '', 1, 4, 3, 1, 1, 3, 0, 3, 36, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (75, '2023-02-14 14:45:05', null, '2023-02-22', 530, null, 'Lápis cor, lápis preto e agulha de desentupir boca de fogão', 2, 1, 4, 2, 3, 10, 0, 3, 37, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (76, '2023-02-14 16:24:59', '2023-02-14', null, null, 108, 'Lápis de cor', 1, 4, 3, 1, 1, 3, 0, 3, 29, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (77, '2023-02-15 12:10:13', '2023-02-15', null, null, 1000, 'Pagamento Cartão de Crédito Bradesco', 2, 4, 3, 6, 14, 67, 0, 3, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (78, '2023-02-24 11:35:41', '2023-02-23', null, null, 213, '', 2, 4, 3, 2, 6, 23, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (79, '2023-02-24 11:44:24', '2023-02-15', null, null, 75, 'Grossa de lapis e toalhas', 1, 1, 3, 1, 1, 1, 0, 2, 10, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (80, '2023-02-24 11:45:54', '2023-02-22', '2023-02-22', 162, 162, '', 1, 4, 3, 1, 1, 3, 0, 3, 39, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (81, '2023-02-24 11:46:57', '2023-02-15', null, null, 288, 'Mochilas e toalhas', 1, 4, 3, 1, 1, 3, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (82, '2023-02-24 11:47:59', '2023-02-23', null, null, 50, 'Mochilas e porta lapis', 1, 4, 3, 1, 1, 3, 0, 3, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (83, '2023-02-24 11:48:37', '2023-03-03', '2023-02-23', 196, 100, 'Mochilas e toalhas', 1, 4, 3, 1, 1, 3, 0, 3, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (84, '2023-02-24 11:50:12', '2023-02-17', null, null, 54, 'Toalhas person.', 1, 1, 3, 1, 1, 1, 0, 2, 41, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (85, '2023-02-24 11:51:22', '2023-02-17', '2023-02-17', 30, 30, 'Colher', 1, 4, 3, 1, 1, 3, 0, 3, 42, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (86, '2023-02-24 11:53:12', '2023-02-24', null, null, 153, '', 1, 1, 3, 1, 1, 1, 0, 2, 43, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (87, '2023-03-04 11:22:13', '2023-02-27', null, null, 2950, 'Havaianas', 2, 4, 3, 2, 3, 10, 0, 3, 45, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (88, '2023-03-04 11:24:03', '2023-02-27', null, null, 670, 'Mochilqs', 2, 4, 3, 2, 3, 10, 0, 3, 44, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (89, '2023-03-04 11:32:15', '2023-03-14', '2023-03-01', 46, 96, 'Restante do pagamento', 1, 4, 3, 1, 1, 3, 0, 4, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (90, '2023-03-04 11:33:53', '2023-03-25', '2023-03-01', 67, 67, 'Restante do pagamento', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (91, '2023-03-06 08:45:10', '2023-03-03', null, null, 310, '', 2, 1, 3, 2, 6, 23, 0, 2, 20, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (92, '2023-03-06 08:48:49', '2023-03-04', null, null, 180, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 2, 35, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (93, '2023-03-06 08:49:32', '2023-03-10', null, null, 225, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (94, '2023-03-06 08:58:13', '2023-02-27', null, null, 120, '', 2, 3, 3, 2, 15, 64, 0, 5, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (95, '2023-03-06 08:58:46', '2023-02-27', null, null, 80, '', 2, 1, 3, 2, 15, 66, 0, 5, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (96, '2023-03-06 08:59:13', '2023-02-27', null, null, 400, '', 2, 1, 3, 2, 15, 63, 0, 5, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (97, '2023-03-07 14:04:02', '2023-03-07', null, null, 16.5, '', 1, 1, 3, 1, 1, 1, 0, 2, 48, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (98, '2023-03-07 14:05:28', '2023-03-23', '2023-03-10', 110, 110, 'Panos de prato', 1, 4, 3, 1, 1, 3, 0, 2, 47, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (99, '2023-03-09 10:59:23', '2023-03-09', null, null, 107, 'Panos de prato', 1, 4, 3, 1, 1, 1, 0, 3, 49, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (100, '2023-03-09 11:04:05', '2023-03-23', '2023-03-20', 476.5, 476.5, 'Havaianas', 1, 1, 3, 1, 1, 3, 0, 3, 50, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (101, '2023-03-09 11:05:02', '2023-04-04', '2023-04-01', 476.5, 353.5, 'Havaianas', 1, 4, 3, 1, 1, 3, 0, 3, 50, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (102, '2023-03-09 11:06:41', '2023-03-07', null, null, 84, 'Panos de chão', 1, 1, 3, 1, 1, 1, 0, 4, 51, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (103, '2023-03-09 11:08:11', '2023-03-07', null, null, 140, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 4, 52, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (104, '2023-03-14 08:45:00', '2023-03-25', '2023-03-20', 294.25, 294.25, 'Materias diversos', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (105, '2023-03-14 08:46:23', '2023-05-03', '2023-03-27', 149.75, 150, 'Materias DIversos', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (106, '2023-03-14 08:46:23', '2023-04-14', '2023-04-03', 294.25, 200, 'Materias DIversos', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (107, '2023-03-14 08:46:23', null, '2023-04-10', 294.25, null, 'Materias DIversos', 1, 1, 4, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (108, '2023-03-14 13:44:55', '2023-03-14', null, null, 236.82, 'Havaianas e extensão', 1, 4, 3, 1, 1, 3, 0, 3, 10, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (109, '2023-03-14 14:06:16', '2023-03-10', null, null, 80, '', 1, 4, 3, 1, 1, 3, 0, 3, 27, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (110, '2023-03-14 14:09:25', '2023-03-11', null, null, 29.52, '', 1, 1, 3, 1, 1, 1, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (111, '2023-03-14 16:25:44', '2023-03-14', null, null, 100, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 4, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (112, '2023-03-14 16:26:37', '2023-04-01', '2023-03-22', 72, 72, 'Havaianas', 1, 4, 3, 1, 1, 3, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (113, '2023-03-14 16:41:24', '2023-03-14', null, null, 100, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 4, 10, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (114, '2023-03-14 17:15:18', '2023-04-05', '2023-03-30', 168, 184, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 2, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (115, '2023-03-14 17:15:18', '2023-04-29', '2023-04-09', 168, 150, 'Havaianas', 1, 1, 3, 1, 1, 1, 0, 2, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (116, '2023-03-14 17:16:17', '2023-03-14', null, null, 22, 'Esc e cola', 1, 1, 3, 1, 1, 1, 0, 4, 40, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (117, '2023-03-27 09:18:04', '2023-03-22', null, null, 50, '', 1, 1, 3, 1, 1, 1, 0, 2, 27, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (118, '2023-03-27 09:21:43', '2023-03-24', null, null, 106, '', 1, 1, 3, 1, 1, 1, 0, 2, 53, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (119, '2023-03-27 10:31:35', '2023-03-14', null, null, 100, '', 2, 1, 3, 2, 6, 23, 0, 4, 1, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (120, '2023-03-27 10:33:39', '2023-03-16', null, null, 56, '', 1, 1, 3, 1, 1, 1, 0, 2, 55, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (121, '2023-04-06 11:14:41', '2023-04-24', null, null, 17.55, '', 2, 3, 3, 2, 2, 8, 0, 3, 54, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (122, '2023-04-06 11:17:12', '2023-04-27', null, null, 4.9, 'Segura da conta PagBank', 2, 3, 3, 2, 2, 8, 0, 3, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (123, '2023-04-06 11:19:52', '2023-04-28', null, null, 315, '', 1, 4, 3, 1, 1, 3, 0, 3, 56, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (124, '2023-04-06 11:22:44', '2023-03-30', null, null, 67, '', 1, 4, 3, 1, 1, 3, 0, 3, 57, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (125, '2023-04-06 11:23:24', '2023-03-30', null, null, 65, '', 1, 1, 3, 1, 1, 1, 0, 2, 57, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (126, '2023-04-06 11:24:56', '2023-03-24', null, null, 123, '', 1, 1, 3, 1, 1, 1, 0, 2, 50, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (127, '2023-04-06 11:28:07', '2023-03-30', null, null, 40, '', 1, 1, 3, 1, 1, 1, 0, 2, 58, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (128, '2023-04-06 11:38:39', '2023-03-30', null, null, 200, '', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (129, '2023-04-11 14:20:34', '2023-04-01', null, null, 40, '', 1, 1, 3, 1, 1, 1, 0, 2, 14, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (130, '2023-04-20 14:28:17', '2023-04-13', null, null, 60, '', 1, 1, 3, 1, 1, 1, 0, 2, 59, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (131, '2023-04-20 14:31:01', '2023-04-14', null, null, 106, '', 1, 1, 3, 1, 1, 1, 0, 2, 60, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (132, '2023-04-20 14:32:50', '2023-04-20', '2023-04-20', 240, 240, '', 1, 1, 3, 1, 1, 1, 0, 2, 61, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (133, '2023-04-20 14:34:18', '2023-04-19', null, null, 106, '', 1, 1, 3, 1, 1, 1, 0, 2, 15, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (134, '2023-04-20 14:35:02', '2023-04-20', '2023-04-20', 100, 205, '', 1, 1, 3, 1, 1, 3, 0, 3, 15, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (135, '2023-04-20 14:37:40', '2023-04-11', null, null, 80, '', 1, 4, 3, 1, 1, 1, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (136, '2023-04-20 14:39:19', null, '2023-04-19', 60, null, '', 1, 1, 4, 1, 1, 3, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (137, '2023-04-20 14:39:19', null, '2023-04-26', 210, null, '', 1, 1, 4, 1, 1, 3, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (138, '2023-04-20 14:52:44', '2023-04-18', null, null, 580, 'Cadeado ao barbear filtro de linha', 2, 4, 3, 2, 3, 10, 0, 3, 62, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (139, '2023-04-22 12:11:55', '2023-04-20', null, null, 953, '', 2, 4, 3, 2, 3, 10, 0, 3, 62, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (140, '2023-04-25 14:54:15', '2023-04-24', null, null, 80, '', 1, 1, 3, 1, 1, 3, 0, 2, 27, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (141, '2023-04-25 14:59:57', '2023-04-24', null, null, 95, '', 1, 4, 3, 1, 1, 3, 0, 3, 63, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (142, '2023-04-25 15:02:28', '2023-04-24', null, null, 30, '', 1, 1, 3, 1, 1, 1, 0, 2, 64, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (143, '2023-04-25 17:34:31', '2023-04-25', null, null, 136, '', 1, 1, 3, 1, 1, 1, 0, 4, 66, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (144, '2023-04-25 17:35:27', '2023-04-25', null, null, 50, '', 1, 1, 3, 1, 1, 1, 0, 4, 13, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (145, '2023-04-25 17:36:22', '2023-04-25', null, null, 50, '', 1, 4, 3, 1, 1, 3, 0, 3, 13, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (146, '2023-04-25 17:37:48', '2023-04-25', null, null, 169.95, '', 1, 1, 3, 1, 1, 1, 0, 4, 65, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (147, '2023-04-25 17:46:52', '2023-04-24', null, null, 26, '', 1, 1, 3, 1, 1, 1, 0, 2, 67, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (148, '2023-04-26 22:36:00', '2023-04-26', null, null, 470, '', 1, 1, 3, 1, 1, 1, 0, 2, 68, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (149, '2023-04-27 14:24:07', '2023-04-26', null, null, 38, '', 1, 1, 3, 1, 1, 1, 0, 2, 69, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (150, '2023-04-27 14:26:26', '2023-04-27', null, null, 80, '', 1, 1, 3, 1, 1, 1, 0, 2, 53, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (151, '2023-04-27 14:28:15', '2023-04-26', null, null, 220, '', 2, 1, 3, 2, 3, 10, 0, 4, 70, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (152, '2023-04-27 14:29:46', '2023-05-04', '2023-05-02', 88, 88, '', 1, 1, 3, 1, 1, 1, 0, 2, 71, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (153, '2023-04-27 17:34:46', null, '2023-04-29', null, 183, '', 1, 1, 3, 1, 1, 1, 0, 2, 11, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (154, '2023-04-27 18:55:41', '2023-04-27', null, null, 50, '', 1, 1, 3, 1, 1, 1, 0, 4, 72, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (155, '2023-04-27 18:57:19', '2023-04-27', null, null, 50, '', 2, 1, 3, 2, 4, 13, 0, 4, 21, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (156, '2023-05-04 15:20:02', '2023-05-01', null, null, 100, 'Toalhinhas', 1, 1, 3, 1, 1, 1, 0, 2, 74, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (157, '2023-05-04 15:21:31', null, '2023-05-03', 37, null, 'Restante toalhinhas', 1, 1, 4, 1, 1, 1, 0, 2, 74, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (158, '2023-05-04 15:23:00', '2023-05-03', null, null, 110, '', 1, 1, 3, 1, 1, 1, 0, 2, 73, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (159, '2023-05-05 16:11:21', '2023-05-04', null, null, 88, '', 2, 1, 3, 2, 6, 23, 0, 4, 1, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (160, '2023-05-05 16:15:20', '2023-05-04', null, null, 420, '', 2, 1, 3, 2, 3, 10, 0, 3, 70, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (161, '2023-05-05 16:18:11', '2023-05-04', null, null, 555, '', 2, 1, 3, 2, 3, 10, 0, 3, 75, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (162, '2023-05-09 14:49:25', '2023-05-08', null, null, 150, '', 1, 4, 3, 1, 1, 3, 0, 3, 38, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (163, '2023-05-09 14:50:51', '2023-05-03', null, null, 150, '', 2, 1, 3, 2, 4, 13, 0, 4, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (164, '2023-05-15 15:34:22', '2023-05-11', null, null, 200, 'Vendas Arnaldo caldas', 1, 1, 3, 1, 1, 1, 0, 4, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (165, '2023-05-15 15:35:18', '2023-05-09', null, null, 68, 'Vendas Arnaldo caldas', 1, 1, 3, 1, 1, 1, 0, 2, 0, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (166, '2023-05-15 16:16:10', '2023-05-15', null, null, 58, 'Cadeado 20', 1, 1, 3, 1, 1, 1, 0, 4, 76, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (167, '2023-05-15 17:03:18', '2023-05-15', null, null, 57, '', 1, 1, 3, 1, 1, 1, 0, 4, 77, 2, 1);
INSERT INTO TB_FLUXO_CAIXA (co_fluxo_caixa, dt_cadastro, dt_realizado, dt_vencimento, nu_valor, nu_valor_pago, ds_descricao, tp_fluxo, tp_pagamento, st_pagamento, co_categoria_fc, co_categoria_fc_filha, co_categoria_fc_neta, co_centro_custo, co_conta_bancaria, co_representacao, co_usuario, co_assinante) VALUES (168, '2023-05-18 16:56:31', '2023-05-18', null, null, 229, '', 1, 1, 3, 1, 1, 1, 0, 4, 0, 2, 1);